[nfs]
172.31.20.57 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/devops.pem

[webservers]
172.31.29.9 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/devops.pem
172.31.20.130 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/devops.pem

[db]
172.31.27.116 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/devops.pem

[lb]
172.31.25.243 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=~/devops.pem
