---
- name: Include dynamic variables
  hosts: all
  tasks:
    - import_playbook: ../static-assignments/common.yml
    - include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Webservers assignment
  hosts: webservers
    - import_playbook: ../static-assignments/webservers.yml


